# top-level: YAML anchors let you mix & match easily
parsers:

  - name: xtb
    type: fincli.parsers.XTBParser
    params:
      cash_file: rawData/XTB/cashOperations.csv
      trades_file: rawData/XTB/tradeOperations.csv
      sep: ";"

processors:
  - name: savings
    type: fincli.processors.SavingPerformanceProcessor
    params:
      year: 2024

  - name: trading
    type: fincli.processors.TradingPerformanceProcessor
    params:
      year: 2024
    

output:
  type: fincli.output.HtmlReportOutput
  params:
    out_file: report.html
