# top-level: YAML anchors let you mix & match easily
parsers:
  - name: tr
    type: fincli.parsers.TradeRepublicParser
    params:
      data_dir: rawData/tradeRepublic          
    
  - name: bingx
    type: fincli.parsers.BingxParser
    params:
      path: rawData/bingX
      fx_csv: utilsData/eurofxref-hist.csv

  - name: binance
    type: fincli.parsers.BinanceParser
    params:
      trades_path: rawData/binance/trades
      savings_path: rawData/binance/rewards
      glob: "*.csv"
      sep: ","
      
  - name: bitget
    type: fincli.parsers.BitGetParser
    params:
      path: rawData/bitget
      glob: "*.csv"
      sep: ";"

  - name: revolut
    type: fincli.parsers.RevolutParser
    params:
      path: rawData/revolut
      glob: "*.csv"
      sep: ";"

  - name: xtb
    type: fincli.parsers.XTBParser
    params:
      cash_file: rawData/XTB/cashOperations.csv
      trades_file: rawData/XTB/tradeOperations.csv
      sep: ";"

  - name: manual
    type: fincli.parsers.ManualInterestParser
    params:
      path: rawData/manualInterest
      glob: "*.csv"
      sep: ";"

processors:
  - name: savings
    type: fincli.processors.SavingPerformanceProcessor
    params:
      year: 2024

  - name: trading
    type: fincli.processors.TradingPerformanceProcessor
    params:
      year: 2024
    

output:
  type: fincli.output.HtmlReportOutput
  params:
  
    out_file: report2.html
